version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: monthly
    labels:
      - "no-changelog"

  - package-ecosystem: "pip"
    directory: /src/test/python_tests
    schedule:
      interval: daily
    labels:
      - "no-changelog"

  - package-ecosystem: "pip"
    groups: { pip-deps: { patterns: ["*"] } }
    directory: /
    schedule:
      interval: daily
    labels:
      - "debt"
    commit-message:
      include: "scope"
      prefix: "pip"

  - package-ecosystem: "npm"
    groups: { node-deps: { patterns: ["*"] } }
    directory: /
    schedule:
      interval: monthly
    labels:
      - "no-changelog"
    ignore:
      - dependency-name: "@types/vscode"
      - dependency-name: "@types/node"
      - dependency-name: "vscode-languageclient"
